export {
  createDestination,
  createHotspot,
  createScene,
  createSceneLink,
  publishDestination,
  publishScene,
  updateDestination,
  updateHotspot,
  updateScene,
  useCreateDestination,
  useCreateHotspot,
  useCreateScene,
  useCreateSceneLink,
  usePublishDestination,
  usePublishScene,
  useUpdateDestination,
  useUpdateHotspot,
  useUpdateScene,
} from '@hatinh/api-client';
